# HIERARCHICAL TREASURY TEAM TASKS
# Treasury Manager coordinates team for payment processing and surplus investment

treasury_coordination_task:
  description: >
    Analyze request: {treasury_request}
    
    Extract payment details and delegate to specialists:
    1. Extract payment amount and recipient
    2. Delegate risk assessment to Risk Assessor
    3. Delegate payment analysis to Payment Specialist
    4. Delegate investment analysis to Market Analyst (if surplus available)
    
  expected_output: >
    Simple coordination plan with task delegation.
    
  task_completion_criteria: >
    - Request analyzed
    - Tasks delegated
    
  agent: treasury_manager
  output_file: output/treasury_report.md

payment_processing_task:
  description: >
    Analyze payment for: {treasury_request}
    
    1. Choose payment method (USDT/USDC preferred)
    2. Calculate costs
    3. Create execution plan
    4. Request user approval
    
  expected_output: >
    Simple payment proposal with method, costs, and approval request.
    
  task_completion_criteria: >
    - Payment method selected
    - Costs calculated
    - Approval requested
    
  # No specific agent - let Treasury Manager delegate in hierarchical process
  context:
    - treasury_coordination_task

market_analysis_task:
  description: >
    Analyze investments for: {treasury_request}
    
    1. Calculate surplus after payment
    2. Check if surplus > $1,000
    3. If yes, suggest conservative investments
    4. Request user approval
    
  expected_output: >
    Simple investment proposal if surplus available.
    
  task_completion_criteria: >
    - Surplus calculated
    - Investment suggested (if applicable)
    - Approval requested
    
  # No specific agent - let Treasury Manager delegate in hierarchical process
  context:
    - treasury_coordination_task
    - payment_processing_task

risk_assessment_task:
  description: >
    Assess risk for: {treasury_request}
    
    1. Check if payment maintains minimum balance
    2. Validate transaction limits
    3. Provide APPROVE/REJECT decision
    
  expected_output: >
    Simple risk assessment with approval decision.
    
  task_completion_criteria: >
    - Balance checked
    - Risk assessed
    - Decision provided
    
  # No specific agent - let Treasury Manager delegate in hierarchical process
  context:
    - treasury_coordination_task

final_treasury_report_task:
  description: >
    Create final report for: {treasury_request}
    
    Combine all specialist results into simple summary:
    1. Risk assessment results
    2. Payment proposal
    3. Investment proposal (if applicable)
    4. Final recommendations
    
  expected_output: >
    Simple final report with all specialist inputs.
    
  task_completion_criteria: >
    - All results combined
    - Final recommendations made
    
  agent: treasury_manager
  context:
    - treasury_coordination_task
    - payment_processing_task
    - market_analysis_task
    - risk_assessment_task
  output_file: output/final_treasury_report.md
