# HIERARCHICAL TREASURY TEAM TASKS
# Treasury Manager coordinates team for payment processing and surplus investment

treasury_coordination_task:
  description: >
    Coordinate treasury operations for the given request: {treasury_request}
    
    As Treasury Manager, analyze the request and coordinate your specialist team:
    
    1. **Request Analysis**: Understand the payment requirements, amounts, recipients, and any investment preferences
    2. **Team Coordination**: Delegate appropriate tasks to specialist agents based on their expertise
    3. **Priority Management**: Ensure payment processing takes absolute priority over investment analysis
    4. **Risk Oversight**: Ensure Risk Assessor validates minimum balance requirements before ANY transaction
    5. **Final Authorization**: Review all specialist recommendations and make executive decisions
    6. **User Approval**: Present final recommendations to user for approval before execution
    
    **Critical Workflow:**
    - Risk Assessor: MUST validate minimum balance before proceeding
    - Payment Specialist: Prepare payment proposal and request user approval before execution
    - Market Analyst: Prepare investment proposal and request user approval (only AFTER payment completion)
    - Treasury Manager: Coordinate team and ensure ALL specialists seek user approval for their actions
    
    **Balance Protection Rules:**
    - NEVER use 100% of account balance
    - ALWAYS maintain user-specified minimum balance
    - Payment + Investment must be < (Total Balance - Minimum Balance)
    - Block transactions that would violate minimum balance requirements
    
  expected_output: >
    A comprehensive treasury operation plan that includes:
    1. Risk assessment results with balance validation
    2. Payment execution strategy and routing recommendations  
    3. Surplus fund analysis and investment opportunities (if applicable)
    4. Final recommendations requiring user approval
    5. Complete audit trail of all decisions and validations
    
    The output must prioritize payment execution while strictly protecting minimum balances
    and present all recommendations to the user for final approval.
    
  agent: treasury_manager
  output_file: output/treasury_report.md

payment_processing_task:
  description: >
    Analyze payment options and prepare execution proposal for: {treasury_request}
    
    **CRITICAL: Present proposal to user for approval before any execution**
    
    1. **Payment Route Analysis**: Evaluate self-custody wallet (USDT/USDC) vs fiat transfer options
    2. **Cost-Speed Optimization**: Balance transaction costs with execution speed requirements
    3. **Method Selection**: Prioritize self-custody wallet transfers, use fiat as backup
    4. **Execution Planning**: Develop step-by-step payment execution strategy
    5. **Risk Coordination**: Work with Risk Assessor to ensure balance requirements are met
    6. **User Approval Request**: Present clear proposal with all details for user authorization
    
    **Payment Preferences:**
    - Self-custody wallet transfers (USDT/USDC) - preferred method
    - Traditional fiat banking - backup option  
    - Cross-border wire transfers - when necessary
    - Optimize for balanced cost-speed ratio
    
    **Approval Framework:**
    - Clearly state: "REQUESTING USER APPROVAL for payment execution"
    - Present all costs, risks, and execution details
    - Wait for explicit user confirmation before proceeding
    - Log approval request in audit trail
    
  expected_output: >
    Payment execution proposal requiring user approval, including:
    1. **APPROVAL REQUEST**: Clear statement requesting user authorization
    2. Optimal payment method and routing strategy with detailed justification
    3. Complete cost breakdown and execution timeline
    4. Technical implementation steps for chosen method
    5. Risk considerations and balance impact assessment
    6. Backup options if primary method fails
    7. **USER ACTION REQUIRED**: Explicit request for go/no-go decision
    
  agent: payment_specialist
  context:
    - treasury_coordination_task

market_analysis_task:
  description: >
    Analyze market conditions and prepare investment proposal for: {treasury_request}
    
    **CRITICAL**: Only proceed if payment processing is successful AND present proposal to user for approval
    
    1. **Surplus Detection**: Calculate available funds after successful payment completion
    2. **Market Analysis**: Evaluate current market conditions for investment opportunities  
    3. **Investment Screening**: Identify conservative investment options suitable for surplus
    4. **Yield Analysis**: Assess potential returns vs risk for recommended investments
    5. **Timing Evaluation**: Determine optimal timing for surplus fund allocation
    6. **User Approval Request**: Present detailed investment proposal for user authorization
    
    **Surplus Calculation Formula:**
    Available Surplus = (Total Balance - Payment Amount - Minimum Balance) * 0.8
    
    **Investment Criteria:**
    - Only analyze if surplus > $1,000 after payment
    - Conservative to moderate risk investments only
    - Focus on yield opportunities that align with user preferences
    - Never recommend using more than 80% of calculated surplus
    
    **Approval Framework:**
    - Clearly state: "REQUESTING USER APPROVAL for investment execution"
    - Present all investment details, risks, and expected returns
    - Wait for explicit user confirmation before proceeding
    - Log approval request in audit trail
    
  expected_output: >
    Investment proposal requiring user approval, including:
    1. **APPROVAL REQUEST**: Clear statement requesting user authorization for investment
    2. Surplus fund calculation and availability assessment
    3. Current market conditions and investment opportunities analysis
    4. Specific investment recommendations with detailed risk-return analysis
    5. Timing recommendations for optimal surplus allocation
    6. Investment limits and safety buffers maintained
    7. **USER ACTION REQUIRED**: Explicit request for investment go/no-go decision
    
    Only provide investment proposal if payment is successful and surplus is available.
    
  agent: market_analyst
  context:
    - treasury_coordination_task
    - payment_processing_task

risk_assessment_task:
  description: >
    Perform comprehensive risk assessment and compliance validation for: {treasury_request}
    
    **MANDATORY VALIDATION** - You have absolute authority to block risky transactions
    
    1. **Balance Validation**: Verify minimum balance requirements will be maintained
    2. **Transaction Limits**: Ensure all amounts are within approved limits
    3. **Compliance Checking**: Validate regulatory and policy compliance
    4. **Risk Scoring**: Assess overall transaction risk profile
    5. **Audit Trail**: Create comprehensive compliance documentation
    
    **Critical Balance Formula:**
    Transaction Allowed = (Payment + Investment) < (Total Balance - Minimum Balance)
    
    **Risk Assessment Criteria:**
    - Minimum balance protection (absolute priority)
    - Transaction amount limits and daily limits
    - Recipient and destination risk evaluation
    - Investment risk assessment (if applicable)
    - Regulatory compliance verification
    
    **Authority Level:** 
    - You can BLOCK any transaction that risks minimum balance violation
    - You must VALIDATE all transactions before execution
    - You have VETO power over risky operations
    
  expected_output: >
    Comprehensive risk assessment including:
    1. Balance validation results (PASS/FAIL with specific calculations)
    2. Transaction risk score and compliance status
    3. Detailed risk breakdown for payment and investment components
    4. Regulatory compliance verification results
    5. Final recommendation (APPROVE/REJECT/MODIFY) with justification
    6. Complete audit trail for compliance purposes
    
    Must explicitly state whether minimum balance requirements will be maintained.
    
  agent: risk_assessor
  context:
    - treasury_coordination_task

final_treasury_report_task:
  description: >
    Synthesize all specialist agent analyses into a comprehensive final treasury report for: {treasury_request}
    
    **MANAGER RESPONSIBILITY**: Gather and integrate all specialist team outputs into one master report
    
    1. **Executive Summary**: High-level overview of the complete treasury operation
    2. **Team Coordination Review**: How the Treasury Manager coordinated specialist agents
    3. **Risk Assessment Integration**: Incorporate Risk Assessor's balance validation and compliance results
    4. **Payment Strategy Integration**: Incorporate Payment Specialist's routing analysis and execution proposal
    5. **Investment Analysis Integration**: Incorporate Market Analyst's surplus detection and investment recommendations
    6. **Final Decision Framework**: Treasury Manager's synthesis of all specialist inputs
    7. **User Approval Summary**: Consolidate all approval requests from specialists into clear action items
    8. **Implementation Plan**: Step-by-step execution plan based on team recommendations
    
    **Report Structure:**
    - Executive Summary (Treasury Manager perspective)
    - Risk Assessment Results (from Risk Assessor)
    - Payment Execution Plan (from Payment Specialist) 
    - Investment Opportunities (from Market Analyst)
    - Manager's Final Recommendations
    - Required User Approvals
    - Next Steps and Implementation Timeline
    
    **Integration Requirements:**
    - Reference specific outputs from each specialist agent
    - Show how Treasury Manager weighed different specialist recommendations
    - Present unified approval requests to user
    - Demonstrate hierarchical decision-making process
    
  expected_output: >
    Comprehensive final treasury report integrating all specialist analyses, including:
    1. **EXECUTIVE SUMMARY**: Treasury Manager's overview of complete operation
    2. **RISK ASSESSMENT SUMMARY**: Key findings from Risk Assessor with balance validation
    3. **PAYMENT STRATEGY SUMMARY**: Payment Specialist's recommendations and approval requests
    4. **INVESTMENT ANALYSIS SUMMARY**: Market Analyst's surplus and investment proposals
    5. **MANAGER'S SYNTHESIS**: How Treasury Manager evaluated and integrated all inputs
    6. **CONSOLIDATED USER APPROVALS**: All approval requests organized by priority
    7. **IMPLEMENTATION ROADMAP**: Clear step-by-step execution plan
    8. **RISK MITIGATION**: How the team addressed balance protection and compliance
    
    The report must demonstrate effective hierarchical coordination and present a unified
    treasury operation plan based on specialist team collaboration.
    
  agent: treasury_manager
  context:
    - treasury_coordination_task
    - payment_processing_task
    - market_analysis_task
    - risk_assessment_task
  output_file: output/final_treasury_report.md
