# HIERARCHICAL TREASURY TEAM TASKS (PROTOTYPE VERSION)
# Treasury Manager coordinates team for payment processing

treasury_coordination_task:
  description: >
    Analyze request: {treasury_request}
    
    You are the Treasury Manager coordinating specialist agents. Your role is to:
    1. Extract payment details (amount, recipient, currency) from the request
    2. Ask questions to specialists to gather their analysis
    3. Coordinate the overall workflow
    
    IMPORTANT: When asking questions to coworkers, use simple string descriptions only.
    For risk assessment, ask: "Please assess the risk for this payment request and check if it maintains minimum balance and meets transaction limits."
    For payment analysis, ask: "Please analyze payment routing options and provide execution recommendations for this request."
    
  expected_output: >
    Simple coordination plan with specialist consultation results.
    
  task_completion_criteria: >
    - Request analyzed
    - Specialists consulted
    - Results coordinated
    
  output_file: output/treasury_report.md

payment_processing_task:
  description: >
    Analyze payment for: {treasury_request}
    
    You are the Payment Specialist. Use the Treasury USDT Payment Tool to:
    1. Choose optimal payment method (USDT/USDC preferred)
    2. Calculate transaction costs and gas fees
    3. Create detailed execution plan
    4. Prepare proposal for user approval
    
    Use the TreasuryUSDTPaymentTool with appropriate actions to analyze and prepare the payment.
    
  expected_output: >
    Detailed payment proposal with method selection, cost analysis, and execution plan ready for approval.
    
  task_completion_criteria: >
    - Payment method analyzed and selected
    - All costs calculated (including gas fees)
    - Execution plan prepared
    - User approval request ready
    
  context:
    - treasury_coordination_task

# Market Analysis Task - Specialist analyzes investment opportunities (COMMENTED OUT FOR PROTOTYPE)
# market_analysis_task:
#   description: >
#     Analyze investments for: {treasury_request}
#     
#     1. Calculate surplus after payment
#     2. Check if surplus > $1,000
#     3. If yes, suggest conservative investments
#     4. Request user approval
#     
#   expected_output: >
#     Simple investment proposal if surplus available.
#     
#   task_completion_criteria: >
#     - Surplus calculated
#     - Investment suggested (if applicable)
#     - Approval requested
#     
#   # No specific agent - let Treasury Manager delegate in hierarchical process
#   context:
#     - treasury_coordination_task
#     - payment_processing_task

risk_assessment_task:
  description: >
    Assess risk for: {treasury_request}
    
    You are the Risk Assessor. Use the Treasury Risk Tools to:
    1. Check if payment maintains minimum balance requirements
    2. Validate transaction against configured limits
    3. Assess overall risk level
    4. Provide clear APPROVE/REJECT decision with reasoning
    
    Use the TreasuryRiskTools with action 'assess_risk' and provide all necessary parameters.
    
  expected_output: >
    Risk assessment report with clear approval/rejection decision and reasoning.
    
  task_completion_criteria: >
    - Balance validation completed
    - Transaction limits checked
    - Risk level assessed
    - Clear decision provided
    
  context:
    - treasury_coordination_task

final_treasury_report_task:
  description: >
    Create final report for: {treasury_request}
    
    Combine all specialist results into simple summary:
    1. Risk assessment results
    2. Payment proposal
    3. Final recommendations
    
  expected_output: >
    Simple final report with all specialist inputs.
    
  task_completion_criteria: >
    - All results combined
    - Final recommendations made
    
  context:
    - treasury_coordination_task
    - payment_processing_task
    - risk_assessment_task
  output_file: output/final_treasury_report.md
